INSERT INTO public.products (id, price, productname) VALUES (5, 159, 'Water');
INSERT INTO public.products (id, price, productname) VALUES (6, 300, 'Meat');
INSERT INTO public.products (id, price, productname) VALUES (7, 3000, 'Wheel');
INSERT INTO public.products (id, price, productname) VALUES (8, 20, 'Oil');
INSERT INTO public.products (id, price, productname) VALUES (9, 2000, 'Desk');
INSERT INTO public.products (id, price, productname) VALUES (10, 10, 'Paper');
INSERT INTO public.products (id, price, productname) VALUES (11, 700, 'Door');
INSERT INTO public.products (id, price, productname) VALUES (12, 5, 'Burger');
INSERT INTO public.products (id, price, productname) VALUES (13, 1, 'Salt');
